# Default values for cray-node-discovery.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: artifactory.algol60.net/csm-docker/stable/cray-node-discovery
  # tag defaults to chart appVersion
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    memory: "50Mi"
    cpu: "1m"
  limits:
    memory: "100Mi"
    cpu: "2"

nodeSelector: {}

tolerations: []

affinity: {}

networks:
  node_management:
    blocks:
      ipv4:
      - label: river
        network: "10.252.0.0/17"
  hardware_management:
    blocks:
      ipv4:
      - label: river
        network: "10.254.0.0/17"
