apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cray-node-discovery.fullname" . }}
  labels:
{{ include "cray-node-discovery.labels" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - configmaps
  verbs:
  - get
  - patch
  - update
