# node-discovery daemonset needs host path and host network
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cray-node-discovery.fullname" . }}
  labels:
{{ include "cray-node-discovery.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: {{ include "cray-node-discovery.fullname" . }}
